stages:
  - test
  - build

variables:
  NODE_ENV: 'development'
  NODE_VERSION: '20.10.0'

cache:
  paths:
    - node_modules/

# Étape de test
test:
  stage: test
  image: node:$NODE_VERSION
  script:
    - npm i
    - npm run test

# Étape de build
build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - master
